### ISSUE TITLE
Player stats request?

### ISSUE THREAD

**Issue by ericgrantholland** [Afischbacher/Nhl.Api#11]
Just started using this package, first of all, fantastic job, very easy to use. 

I'm looking to get player stats by year, it seems like the 3rd party API supports getting stats for a specific player.
https://github.com/dword4/nhlapi#people

Could this request be supported here also?

**Comment by Afischbacher** [comment]
Hey @ericgrantholland 

I have just release v1.2.0 with the request endpoint completed! 

https://www.nuget.org/packages/Nhl.Api/1.2.0

Thank you so much for opening the ticket request and please key them coming!
