### ISSUE TITLE
Include on-ice players with live feed data

### ISSUE THREAD

**Issue by andersme** [Afischbacher/Nhl.Api#21]
It would be really excellent if the plays from the live feed included the players that were on the ice at the time of the play. This can be determined by pulling in data from:

https://api.nhle.com/stats/rest/en/shiftcharts?cayenneExp=gameId=${gamePk}

Having the team strength (5v5, 5v4, etc.) could also be gleamed from this data.

**Comment by Afischbacher** [comment]
Hey @andersme

Thanks for opening this issue, I appreciate it, I love idea 💡 and will get it in for 1.7.0

I may ask you for some clarification on exactly what you are looking for.

Thanks again

**Comment by andersme** [comment]
Probably just an array of player ids on the ice for each event. This is useful for calculating Corsi numbers or expected goals stats.

**Comment by andersme** [comment]
That would be good. But it would be better if they were split into to arrays, one for the offensive players for that play and one for the defensive players.

**Comment by Afischbacher** [comment]
Yeah that would be something to consider for that as well, good point @andersme I will probably get you to look at the pull request once I have it ready

**Comment by andersme** [comment]
Sounds good. I appreciate all your hard work on this.

**Comment by Afischbacher** [comment]
Hey @andersme,

I don't want to hold up the 1.7.0 release, so for now I will just implement the players on ice and split them by home and away teams for now in 2 separate arrays, such as this and then you can open up another issue for specifically determining which team is the offensive or defensive team. 

Thanks again!
 
Best Regards

**Comment by andersme** [comment]
That sounds perfectly reasonable, thanks!

**Comment by Afischbacher** [comment]
https://github.com/Afischbacher/Nhl.Api/pull/24

**Comment by Afischbacher** [comment]
Released v1.70! So I will close this issue :) 👍
