### ISSUE TITLE
Get game schedule for season

### ISSUE THREAD

**Issue by andersme** [Afischbacher/Nhl.Api#22]
Currently, there are a couple of methods to get the current day's schedule and by date. There are a few additional endpoints that the NHL API exposes for getting schedules. In particular I'm looking to use the endpoint that gets the schedule for a particular season in order to know what games to download for that season.

**Comment by Afischbacher** [comment]
Hey @andersme ,

Sure I can build that out for you for 1.7.0 

I will get that into the pull request coming up in the coming days!

Thanks again

**Comment by Afischbacher** [comment]
https://github.com/Afischbacher/Nhl.Api/pull/24/files

**Comment by Afischbacher** [comment]
Released v1.70! So I will close this issue :) 👍
