### ISSUE TITLE
boxscore is null for me

### ISSUE THREAD

**Issue by justin-m-5** [Afischbacher/Nhl.Api#53]
<img width="604" alt="Screenshot 2024-03-22 at 11 13 53 AM" src="https://github.com/Afischbacher/Nhl.Api/assets/159802767/b770d8c1-f2ef-4a08-b9f9-0768652e9eb8">

**Comment by Afischbacher** [comment]
Hey @justin-m-5,

Looks like our friends down at the NHL decided restructure the response of the JSON payload. For what reason, I have no clue or idea.

Let me try and fix this as soon as possible, thanks for bringing this to my attention.

Thanks,
@Afischbacher

**Comment by justin-m-5** [comment]
haha sounds good and no problem,

thanks for the response and for creating the dot net api.
