### ISSUE TITLE
Exception on PlayerProfile.Age

### ISSUE THREAD

**Issue by bcontant** [Afischbacher/Nhl.Api#55]
If BirthDate is null, Age property will trigger an exception.   

(Ex : https://api-web.nhle.com/v1/player/8457344/landing)

**Comment by Afischbacher** [comment]
Hey @bcontant 

Thanks for bringing this to my attention, I will put a fix in and release 3.4.2

Thanks!

**Comment by Afischbacher** [comment]
Here is the current pull request @bcontant 

https://github.com/Afischbacher/Nhl.Api/pull/56

**Comment by Afischbacher** [comment]
Hey @bcontant 

This has been fixed and released! Thanks!
