### ISSUE TITLE
NhlApi.GetTeamStatisticsBySeasonAndGameTypeAsync Not Returning Correct Results

### ISSUE THREAD

**Issue by calvnnhobs** [Afischbacher/Nhl.Api#57]
Hi,

The following returns what looks like an incomplete result when compared with the corresponding hockey reference page. I tried a few Sharks' seasons prior and those seem fine, its just this season that is giving trouble. Possibly pebcak!

**To reproduce:**
NhlApi.GetTeamStatisticsBySeasonAndGameTypeAsync((int)TeamEnum.SanJoseSharks, "20232024", Nhl.Api.Enumerations.Game.GameType.RegularSeason);

**Comparing to hockey-reference:**
https://www.hockey-reference.com/teams/SJS/2024.html#all_skaters
- expecting 41 skaters and 5 goalies, getting 24 skaters and 3 goalies

Thanks for the API!

**Comment by Afischbacher** [comment]
Hey @calvnnhobs !

Thanks for bringing this to my attention! It looks like the API might be returning incomplete data for the specified season. Let me take a look and see if there is anything I can find that is off/odd.

In the meantime, could you confirm if you're seeing this issue with other teams for the same season, or is it isolated to the San Jose Sharks? Additionally, if you have any more details on how you're using the API or specific patterns you've noticed, that would help us diagnose the issue faster.

I appreciate your patience, and I am super happy you're finding the API useful!

Thanks,
@Afischbacher

**Comment by calvnnhobs** [comment]
@Afischbacher I just tried the same call for the Canucks and encountered the same issue for the last season:

- season 20232024 returns 20 skaters and 2 goalies, but should be 29 skaters and 3 goalies
- 20222023 returns 38 skaters and 4 goalies, as expected
- 20212022 returns 33 skaters and 4 goalies, as expected
- 20112012 returns 33 skaters and 2 goalies, as expected

This is the only issue I've encountered thus far. At the moment I'm just running one-off tests as I assess how I want to collect some statistics for my project. I'm doing this in .NET/C#, using Nuget 3.4.1.

Thanks very much.

**Comment by Afischbacher** [comment]
Hey @calvnnhobs 

I took the raw payload from the REST API here `/club-stats/SJS/20232024/2` and I am getting back as well the same results from the NuGet v3.4.1, as this is the direct response from the REST API, upon reviewing the data, it looks to be for all teams in the 2023/2024 season, my suggestion to you is to use a collection of all of these requests, merge the collections distinctly.

See below: 

 `/club-stats/SJS/20232024/2` 
 `/club-stats/SJS/20242025/2` 

This may yield a better result, but unfortunately I am at the mercy of the data from the NHL, if what I have suggested works for your use case, please let me know and we can close this issue. 

The only other solution I have is to query all active players in the NHL and then filter by the stats for 2023/2024 and then construct a "Roster", I can do this, but it would take me a bit of time.

Thanks,
Andre

**Comment by calvnnhobs** [comment]
All good @Afischbacher, I appreciate you looking into it. You can close it.
