### ISSUE TITLE
Get Other Player Statistics Reports

### ISSUE THREAD

**Issue by calvnnhobs** [Afischbacher/Nhl.Api#58]
Hi,

The NhlStatisticsApi.GetPlayerStatisticsBySeasonAndFilterExpressionAsync method is currently fixed on only returning the "summary" report. Would it be possible to add another method that allows us to return other reports, such as Time On Ice (timeonice) and Miscellaneous (realtime)? Basically this lines up exactly with the reports/statistics found at the main nhl.com stats page, https://www.nhl.com/stats/skaters. 

Some example reports:
https://api.nhle.com/stats/rest/en/skater/timeonice?limit=-1&start=0&cayenneExp=seasonId=20232024
https://api.nhle.com/stats/rest/en/skater/realtime?limit=-1&start=0&cayenneExp=seasonId=20232024

You could potentially expand the PlayerStatisticsResult object to include the additional fields across the various reports. It's maybe the quicker/dirtier way, but there's already some overlap between reports around core data (name, position, shootsCatches) and would simplify the work involved. 

If this is something you'd like help with, let me know. I might rig something up in the short term anyway so I can get those reports in the context of your NhlStatisticsApi class.

Thanks as always.

**Comment by Afischbacher** [comment]
Hey @calvnnhobs

I think this is a great suggestion and I would love to implement this for the NuGet package, I will bundle it with the 3.5.0 update which includes all of the Utah Hockey Club updates! 

Thanks!

**Comment by Afischbacher** [comment]
@calvnnhobs 

I have just released v3.5.0, please take a peek and see if it does the job!

If you're all good here I can close this issue out.

Thanks!

**Comment by calvnnhobs** [comment]
This looks good, thanks @Afischbacher!
