### ISSUE TITLE
Goalie Stats Fail - Nhl.Api.GetGoalieStatisticsBySeasonAndFilterExpressionAsync

### ISSUE THREAD

**Issue by calvnnhobs** [Afischbacher/Nhl.Api#59]
Hi, I'm getting a few fatal errors in the data set when calling Nhl.Api.GetGoalieStatisticsBySeasonAndFilterExpressionAsync, due to unexpectedly null properties:

-otLosses is null (no such thing in 90-91):
https://api.nhle.com/stats/rest/en/goalie/summary?limit=-1&start=0&cayenneExp=seasonId=19901991

-Jose Theodore has a null otLosses in a season that does have otLosses:
https://api.nhle.com/stats/rest/en/goalie/summary?limit=-1&start=0&cayenneExp=seasonId=20052006

-Rob McVicar has a null save percentage (he played a game where he made no saves):
https://api.nhle.com/stats/rest/en/goalie/summary?limit=-1&start=0&cayenneExp=seasonId=20052006

**Comment by Afischbacher** [comment]
Hey @calvnnhobs 

Let me take a look into these cases as well, great work for finding these!

Thanks

**Comment by calvnnhobs** [comment]
Thank you @Afischbacher 

One other note, I can't find a way to restrict the results to regular season or postseason games. The cayenneExp seems fixed to just the seasonId. If we could also specify the game type (as below), that would be helpful.

https://api.nhle.com/stats/rest/en/goalie/summary?limit=-1&start=0&cayenneExp=seasonId=20222023%20and%20gameTypeId=2

**Comment by Afischbacher** [comment]
@calvnnhobs 

Just released v3.5.0 with the fixes that are mentioned in this issue, please let me know if you're satisfied and I can close this out!

**Comment by Afischbacher** [comment]
> goalie/summary?

@calvnnhobs 
Apologies here, this will be released in v3.6.0 as I did not implement this in v3.5.0, I should have the next version out soon!

Thanks!

**Comment by calvnnhobs** [comment]
Hi @Afischbacher, I'll wait until 3.6.0 to check this one then.

**Comment by Afischbacher** [comment]
Hey @calvnnhobs,

This should now be released in v3.6.0, please take a look and reply if everything looks good :)

Thanks!

**Comment by calvnnhobs** [comment]
This looks good @Afischbacher thank you!

**Comment by Afischbacher** [comment]
@calvnnhobs Awesome, will close this issue 👍
